version: 2
meta:
  test_defaults: &test_defaults
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: run tests
          command: |
            ruby -v
            bundle exec rake
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
  "ruby-2.5":
    <<: *test_defaults
    docker:
      - image: circleci/ruby:2.5
  "ruby-2.4":
    <<: *test_defaults
    docker:
      - image: circleci/ruby:2.4
  "ruby-2.3":
    <<: *test_defaults
    docker:
      - image: circleci/ruby:2.3

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - "ruby-2.5":
          requires:
            - checkout_code
      - "ruby-2.4":
          requires:
            - checkout_code
      - "ruby-2.3":
          requires:
            - checkout_code
