version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake
